# Generated by Django 6.1 on 2026-09-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_image_url',
        ),
    ]
