# Generated by Django 6.1 on 2026-09-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
    ]
